apiVersion: v2
name: k8s-promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
version: 0.0.0-replaceme
appVersion: "0.0.0-replaceme"
dependencies:
  - name: promtail
    version: 6.15.2
    repository: https://grafana.github.io/helm-charts

annotations:
  # For k8s-loki it is important to include "prerelease"-versions like "2.9.1-2", so there must be a "-0" after the patch-version.
  # see https://helm.sh/docs/chart_best_practices/dependencies/#prerelease-versions for more information
  "k8s.cloudogu.com/ces-dependency/k8s-loki": "^2.9.1-0, ^3.0.0-0"