# This file contains mapping information for log levels of this component
apiVersion: v1
metavalues:
  mainLogLevel:
    name: Log-Level
    description: The central configuration value to set the log level for this component
    keys:
      - path: promtail.server.config.log_level
        mapping:
          debug: debug
          info: info
          warn: warn
          error: error